version: '3.9'

services:
  redis:
    image: redis:8-alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass prettypass
    restart: unless-stopped
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: "livelib"
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "coolprettypass"
    restart: unless-stopped
    ports:
      - "5444:5432"
    command: -p 5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d livelib"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
  pg_data:

networks:
  backend:
    driver: bridge